#ifndef JSEDITORTOOLS_GLOBAL_H
#define JSEDITORTOOLS_GLOBAL_H

#include <qglobal.h>

#if defined(JSEDITORTOOLS_LIBRARY)
#  define JSEDITORTOOLS_EXPORT Q_DECL_EXPORT
#else
#  define JSEDITORTOOLS_EXPORT Q_DECL_IMPORT
#endif

#endif // JSEDITORTOOLS_GLOBAL_H
